name:                hal
description:         A runtime environment for Haskell applications running on AWS Lambda.
synopsis:            Please see the README.md file for this project.
version:             0.1.0
github:              Nike-inc/hal
license:             BSD3
author:              Nike, Inc.
maintainer:          nikeoss
copyright:           2018 Nike, Inc.
category:            Web,AWS
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - OverloadedStrings
  - BangPatterns
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - OverloadedStrings
  - PatternSynonyms
  - ScopedTypeVariables

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns

library:
  source-dirs: src
  dependencies:
    - aeson < 2.0.0
    - bytestring < 1.0.0
    - envy < 2.0.0
    - http-conduit < 3.0.0
    - http-types < 1.0.0
    - exceptions < 1.0.0
    - mtl < 3.0.0
    - containers < 1.0.0
    - time < 2.0.0
    - text < 2.0.0
