AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Test for the Haskell Runtime.
Resources:
  helloworld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: NOT_USED
      Runtime: provided
      CodeUri: examples/.stack-work/docker/_home/.local/bin/
      Events:
        GetResource:
          Type: Api
          Properties:
            Method: GET
            Path: "/"
      Description: Test for the Haskell Runtime.
      MemorySize: 128
      Timeout: 3
