name:                examples
version:             0.1.0
license:             BSD3
author:              Nike, Inc.
copyright:           2018 Nike, Inc.
category:            Web,AWS
extra-source-files:
- README.md

default-extensions:
  - OverloadedStrings

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fno-warn-partial-type-signatures
  - -fno-warn-name-shadowing
  - -fwarn-tabs
  - -fwarn-unused-imports
  - -fwarn-missing-signatures
  - -fwarn-incomplete-patterns

dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson
  - hal

executables:
  simple:
    source-dirs: simple
    main: Main.hs
  simple-context:
    source-dirs: simplecontext
    main: Main.hs
  fallible:
    source-dirs: fallible
    main: Main.hs
    dependencies:
      - unordered-containers
  value:
    source-dirs: value
    main: Main.hs
    dependencies:
      - mtl
