name: Stack Haskell Builds

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        resolver:
          - lts-11
          - lts-12
          - lts-13
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Stack
        run: |
          export PATH=$HOME/.local/bin:$PATH
          mkdir -p ~/.local/bin
          curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      - name: Install Project Dependencies
        run: |
          set -ex
          stack --no-docker --no-terminal --install-ghc --resolver $RESOLVER test --bench --only-dependencies
          set +ex
        env:
          RESOLVER: ${{ matrix.resolver }}
      - name: Build Project
        run: |
          set -ex
          stack --no-docker --no-terminal --resolver $RESOLVER test --bench --no-run-benchmarks --haddock --no-haddock-deps
          set +ex
        env:
          RESOLVER: ${{ matrix.resolver }}
